buttons:
    but1_n: Чай
    but1_m: 13
    but2_n: Фильтр
    but2_m: 7
    but3_n: Макароны
    but3_m: 8
    but4_n: Духовка
    but4_m: 40
    but5_n: Яйцо
    but5_m: 4
    but6_n: Выбор
    but6_m: 12
